--------------------------------------------------------
--  File created - Saturday-December-05-2020   
--------------------------------------------------------
DROP TABLE "HOSPITALDBA"."DEPARTMENT" cascade constraints;
DROP TABLE "HOSPITALDBA"."DOCTOR" cascade constraints;
DROP TABLE "HOSPITALDBA"."EFFECT" cascade constraints;
DROP TABLE "HOSPITALDBA"."EMPLOYEE" cascade constraints;
DROP TABLE "HOSPITALDBA"."EXAMINATION" cascade constraints;
DROP TABLE "HOSPITALDBA"."INPATIENT" cascade constraints;
DROP TABLE "HOSPITALDBA"."MEDICATION" cascade constraints;
DROP TABLE "HOSPITALDBA"."NONAME" cascade constraints;
DROP TABLE "HOSPITALDBA"."NURSE" cascade constraints;
DROP TABLE "HOSPITALDBA"."OUTPATIENT" cascade constraints;
DROP TABLE "HOSPITALDBA"."PHONE" cascade constraints;
DROP TABLE "HOSPITALDBA"."PRESCRIPT" cascade constraints;
DROP TABLE "HOSPITALDBA"."TREAT" cascade constraints;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."DEPARTMENT" 
   (	"DEPARTMENTCODE" NUMBER(*,0), 
	"DEANCODE" NUMBER(*,0), 
	"TITLE" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCTOR
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."DOCTOR" 
   (	"DCODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EFFECT
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."EFFECT" 
   (	"MED_CODE" NUMBER(*,0), 
	"EFFECT_DESCRIPTION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."EMPLOYEE" 
   (	"ECODE" NUMBER(*,0), 
	"GENDER" CHAR(1 BYTE), 
	"BIRTHDATE" DATE, 
	"FNAME" VARCHAR2(15 BYTE), 
	"LNAME" VARCHAR2(15 BYTE), 
	"STARTDATE" DATE, 
	"DEG_NAME" VARCHAR2(30 BYTE), 
	"DEG_YEAR" NUMBER(*,0), 
	"ADDRESS" VARCHAR2(30 BYTE), 
	"DEPARTMENTCODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXAMINATION
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."EXAMINATION" 
   (	"DOC_CODE" NUMBER(*,0), 
	"OP_CODE" VARCHAR2(7 BYTE), 
	"EXAM_DATE" DATE, 
	"SECOND_EXAM_DATE" DATE, 
	"DIAGNOSIS" VARCHAR2(4000 BYTE), 
	"FEE" NUMBER(7,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INPATIENT
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."INPATIENT" 
   (	"IPCODE" VARCHAR2(7 BYTE), 
	"IP_DOB" DATE, 
	"IP_GENDER" CHAR(1 BYTE), 
	"IP_ADDRESS" VARCHAR2(30 BYTE), 
	"IP_FNAME" VARCHAR2(15 BYTE), 
	"IP_LNAME" VARCHAR2(15 BYTE), 
	"IP_PHONE_NO" VARCHAR2(12 BYTE), 
	"SICK_ROOM" NUMBER(*,0), 
	"IP_DIAGNOSTIC" VARCHAR2(4000 BYTE), 
	"FEE" NUMBER(7,2), 
	"ADMISSION_DATE" DATE, 
	"NCODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICATION
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."MEDICATION" 
   (	"MED_CODE" NUMBER(*,0), 
	"MED_NAME" VARCHAR2(20 BYTE), 
	"MED_DATE" DATE, 
	"PRICE" NUMBER(7,2), 
	"EXPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NONAME
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."NONAME" 
   (	"MNAME" VARCHAR2(10 BYTE), 
	"MID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NURSE
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."NURSE" 
   (	"NCODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OUTPATIENT
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."OUTPATIENT" 
   (	"OPCODE" VARCHAR2(7 BYTE), 
	"OP_DOB" DATE, 
	"OP_GENDER" CHAR(1 BYTE), 
	"OP_ADDRESS" VARCHAR2(30 BYTE), 
	"OP_FNAME" VARCHAR2(15 BYTE), 
	"OP_LNAME" VARCHAR2(15 BYTE), 
	"OP_PHONE_NO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PHONE
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."PHONE" 
   (	"ECODE" NUMBER(*,0), 
	"PHONE" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRESCRIPT
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."PRESCRIPT" 
   (	"DOC_CODE" NUMBER(*,0), 
	"OP_CODE" VARCHAR2(7 BYTE), 
	"MED_CODE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TREAT
--------------------------------------------------------

  CREATE TABLE "HOSPITALDBA"."TREAT" 
   (	"DOC_CODE" NUMBER(*,0), 
	"IPCODE" VARCHAR2(7 BYTE), 
	"MED_CODE" NUMBER(*,0), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"RESULT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOSPITALDBA.DEPARTMENT
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.DOCTOR
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.EFFECT
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.EXAMINATION
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.INPATIENT
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.MEDICATION
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.NONAME
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.NURSE
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.OUTPATIENT
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.PHONE
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.PRESCRIPT
SET DEFINE OFF;
REM INSERTING into HOSPITALDBA.TREAT
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table EFFECT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."EFFECT" ADD PRIMARY KEY ("MED_CODE", "EFFECT_DESCRIPTION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 166 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXAMINATION
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."EXAMINATION" ADD PRIMARY KEY ("DOC_CODE", "OP_CODE", "EXAM_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INPATIENT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."INPATIENT" ADD PRIMARY KEY ("IPCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NURSE
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."NURSE" ADD PRIMARY KEY ("NCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREAT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."TREAT" ADD PRIMARY KEY ("DOC_CODE", "IPCODE", "MED_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."EMPLOYEE" ADD PRIMARY KEY ("ECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSPITALDBA"."EMPLOYEE" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "HOSPITALDBA"."EMPLOYEE" MODIFY ("FNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."DEPARTMENT" ADD PRIMARY KEY ("DEPARTMENTCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSPITALDBA"."DEPARTMENT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HOSPITALDBA"."DEPARTMENT" MODIFY ("DEANCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCTOR
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."DOCTOR" ADD PRIMARY KEY ("DCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OUTPATIENT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."OUTPATIENT" ADD PRIMARY KEY ("OPCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSPITALDBA"."OUTPATIENT" MODIFY ("OP_LNAME" NOT NULL ENABLE);
  ALTER TABLE "HOSPITALDBA"."OUTPATIENT" MODIFY ("OP_FNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICATION
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."MEDICATION" ADD PRIMARY KEY ("MED_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."DEPARTMENT" ADD CONSTRAINT "FK_DEPARMENT_DOCTOR" FOREIGN KEY ("DEANCODE")
	  REFERENCES "HOSPITALDBA"."DOCTOR" ("DCODE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCTOR
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."DOCTOR" ADD CONSTRAINT "FK_DOCTOR_EMPLOYEE" FOREIGN KEY ("DCODE")
	  REFERENCES "HOSPITALDBA"."EMPLOYEE" ("ECODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EFFECT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."EFFECT" ADD CONSTRAINT "FK_EFF_MEDICATION" FOREIGN KEY ("MED_CODE")
	  REFERENCES "HOSPITALDBA"."MEDICATION" ("MED_CODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."EMPLOYEE" ADD CONSTRAINT "FK_EMP_DEPT" FOREIGN KEY ("DEPARTMENTCODE")
	  REFERENCES "HOSPITALDBA"."DEPARTMENT" ("DEPARTMENTCODE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAMINATION
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."EXAMINATION" ADD CONSTRAINT "FK_EXAMINATION_DOCTOR" FOREIGN KEY ("DOC_CODE")
	  REFERENCES "HOSPITALDBA"."DOCTOR" ("DCODE") ENABLE;
  ALTER TABLE "HOSPITALDBA"."EXAMINATION" ADD CONSTRAINT "FK_EXAMINATION_OUTPATIEN" FOREIGN KEY ("OP_CODE")
	  REFERENCES "HOSPITALDBA"."OUTPATIENT" ("OPCODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INPATIENT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."INPATIENT" ADD CONSTRAINT "FK_INPATIENT_NURSE" FOREIGN KEY ("NCODE")
	  REFERENCES "HOSPITALDBA"."NURSE" ("NCODE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NURSE
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."NURSE" ADD CONSTRAINT "FK_NURSE_EMPLOYEE" FOREIGN KEY ("NCODE")
	  REFERENCES "HOSPITALDBA"."EMPLOYEE" ("ECODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHONE
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."PHONE" ADD CONSTRAINT "FK_PHONE_EMPLOYEE" FOREIGN KEY ("ECODE")
	  REFERENCES "HOSPITALDBA"."EMPLOYEE" ("ECODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESCRIPT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."PRESCRIPT" ADD CONSTRAINT "FK_PRESCRIPT_MEDICATION" FOREIGN KEY ("MED_CODE")
	  REFERENCES "HOSPITALDBA"."MEDICATION" ("MED_CODE") ON DELETE SET NULL ENABLE;
  ALTER TABLE "HOSPITALDBA"."PRESCRIPT" ADD CONSTRAINT "FK_PRESCRIPT_OUTPATIENT" FOREIGN KEY ("OP_CODE")
	  REFERENCES "HOSPITALDBA"."OUTPATIENT" ("OPCODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TREAT
--------------------------------------------------------

  ALTER TABLE "HOSPITALDBA"."TREAT" ADD CONSTRAINT "FK_TREAT_DOCTOR" FOREIGN KEY ("DOC_CODE")
	  REFERENCES "HOSPITALDBA"."DOCTOR" ("DCODE") ENABLE;
  ALTER TABLE "HOSPITALDBA"."TREAT" ADD CONSTRAINT "FK_TREAT_INPATIENT" FOREIGN KEY ("IPCODE")
	  REFERENCES "HOSPITALDBA"."INPATIENT" ("IPCODE") ENABLE;
  ALTER TABLE "HOSPITALDBA"."TREAT" ADD CONSTRAINT "FK_TREAT_MEDICATION" FOREIGN KEY ("MED_CODE")
	  REFERENCES "HOSPITALDBA"."MEDICATION" ("MED_CODE") ENABLE;
